version: '3'
services:
  db:
     image: postgres:latest
     restart: always
     environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: r0uei
        TZ: "Asia/Tokyo"
     ports:
        - 5432:5432
     volumes:
        - db-store:/var/lib/postgresql/data
  r0uei:
    platform: linux/aarch64
    image: "r0uei:0.1.0"
    container_name: "r0uei"
    build:
      context: ./app
      dockerfile: Dockerfile
    command: ["./wait-for-postgres.sh", "db", "bundle", "exec", "rackup", "-p", "4567", "-o", "0.0.0.0"]
    ports:
      - 4567:4567
    volumes:
      - ./app:/usr/src/app:cached
    depends_on:
        - db
    stdin_open: true
volumes:
  db-store:
